In [7]:
import pandas as pd
import numpy as np

data = {
    'Date': pd.date_range('2023-01-01', periods=120),

    'Product': (
        ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'] * 15
    ),

    'Region': (
        [
            'East', 'West', 'North', 'South',
            'Central', 'Northeast', 'Northwest', 'Southeast'
        ] * 15
    ),

    'Sales': np.random.randint(100, 5000, 120),

    'Units': np.random.randint(10, 500, 120),

    'Rep': (
        [
            'John', 'Mary', 'Bob', 'Alice',
            'David', 'Emma', 'Michael', 'Sophia',
            'James', 'Olivia', 'Daniel', 'Charlotte'
        ] * 10
    )
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()

df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

df

          Date Product     Region  Sales  Units        Rep    Month Quarter
0   2023-01-01       A       East    966     22       John  January      Q1
1   2023-01-02       B       West   2516     72       Mary  January      Q1
2   2023-01-03       C      North   3198    414        Bob  January      Q1
3   2023-01-04       D      South    139    175      Alice  January      Q1
4   2023-01-05       E    Central   2125    162      David  January      Q1
..         ...     ...        ...    ...    ...        ...      ...     ...
115 2023-04-26       D      South   3629    129     Sophia    April      Q2
116 2023-04-27       E    Central   1342    239      James    April      Q2
117 2023-04-28       F  Northeast   1552    413     Olivia    April      Q2
118 2023-04-29       G  Northwest   1010    354     Daniel    April      Q2
119 2023-04-30       H  Southeast   2537    380  Charlotte    April      Q2

[120 rows x 8 columns]

In [10]:
pd.pivot_table(df, values='Sales', index='Product' ,columns='Month')

Month          April     February  January    March
Product
A        1940.333333  1705.500000  2343.25  1974.00
B        3613.666667  2172.000000  2578.00  1868.25
C        2144.250000  2824.750000  2955.75  1953.00
D        1975.500000  1669.333333  1984.50  2039.00
E        1830.000000  4190.000000  1828.25  1484.50
F        2279.000000  1689.000000  3489.50  2188.00
G        1949.250000  2449.000000  2796.50  2715.25
H        2194.000000  3526.000000  1369.00   775.50